# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment to ec2

on:
  push:
    branches: 
    - dev
    - main

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      with:
        path: $PROJECT_PATH
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: eval "cp ~/config-injection/ecosystem-${NODE_ENV}.json $PROJECT_PATH/ecosystem.json"
    - run: eval "cp ~/config-injection/.env $PROJECT_PATH/.env"
    - run: eval "$PROJECT_PATH/script/prebuild.sh"
    - run: eval "$PROJECT_PATH/script/reload.sh"
    env:
      PROJECT_PATH: ~/actions-runner/_work/A.fume.Server-${NODE_ENV}/
